name: SSH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  # schedule:
  #   - cron: '* */5 * * *'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  token: ${{ secrets.TOKEN_GITHUB }}

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "linux"
  linux:
    # if: false #use to disable the job

    runs-on: ubuntu-latest
    # timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Read authorized public key
        id: read_pub_key
        run: |
          echo "::set-output nwith:          persist-credentials: falseame=pub_key::$(cat authorized_key.pub)"

      - name: Set up Git credentials
        run: |
          git config --global user.name Hiro
          git config --global user.email "laciferin@gmail.com"
          git config --global credential.helper store
          echo "export GITHUB_TOKEN=${{ env.token }}" >> $GITHUB_ENV

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        timeout-minutes: 600
        with:
          # ssh-known-hosts: ${{ steps.read_pub_key.outputs.pub_key }}
          limit-access-to-actor: true 
          limit-access-to-users: Nasfame,pythoneerHiro 

  # This workflow contains a single job called "mac"
  mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        timeout-minutes: 600
        with:
          # ssh-known-hosts: ${{ steps.read_pub_key.outputs.pub_key }}
          limit-access-to-actor: true 
          limit-access-to-users: Nasfame,pythoneerHiro 
