name: SSH

# concurrency:
#   group: ssh
#   cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '* */5 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upterm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Read authorized public key
        id: read_pub_key
        run: |
         echo "::set-output name=pub_key::$(cat authorized_key.pub)"

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          authorized-keys: ${{ steps.read_pub_key.outputs.pub_key }}



      # - name: Run endless
      #   run: |
      #     echo "Sleeping"
      #     sleep 21600; #6hours

