name: SSH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  # schedule:
  #   - cron: '* */5 * * *'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  token: ${{ secrets.TOKEN_GITHUB }}

permissions:
  contents: write
  pull-requests: write
  issues: read
  packages: none


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "linux"
  linux:
    # if: false #use to disable the job

    runs-on: ubuntu-latest
    # timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true #implicit access to the token to every step
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - uses: actions/setup-node@v3
        with:
          node-version: 19
          check-latest: true

      - name: Set up Git credentials
        run: |
          sudo snap install ngrok
          git config --global user.name Nasfame
          git config --global user.email "laciferin@gmail.com"
          git config --global credential.helper '!f() { echo "username=Nasfame\npassword=$token"; }; f'

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        timeout-minutes: 600
        with:
          # ssh-known-hosts: ${{ steps.read_pub_key.outputs.pub_key }}
          limit-access-to-actor: true 
          limit-access-to-users: Nasfame,pythoneerHiro 

  # This workflow contains a single job called "mac"
  mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Git credentials
        run: |
          git config --global user.name Nasfame
          git config --global user.email "laciferin@gmail.com"
          git config --global credential.helper '!f() { echo "username=Nasfame\npassword=$token"; }; f'

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        timeout-minutes: 600
        with:
          # ssh-known-hosts: ${{ steps.read_pub_key.outputs.pub_key }}
          limit-access-to-actor: true 
          limit-access-to-users: Nasfame,pythoneerHiro 
